services:
  kafka:
    image: bitnamilegacy/kafka:3.9.0
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-init:
    image: bitnamilegacy/kafka:3.9.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c", "
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic clicks --partitions 1 &&
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic some_clicks --partitions 2 &&
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic ooo_clicks --partitions 1 &&
      echo 'topics ready'"]

  jobmanager:
    build: .
    container_name: flink-jobmanager
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    ports:
      - "8081:8081"

  taskmanager:
    build: .
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4

  producer:
    build: ./producer
    container_name: click-producer
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - RATE_PER_SECOND=50

  sql-client:
    build: .
    depends_on:
      - jobmanager
      - taskmanager
      - kafka-init
    command:
      - /bin/bash
      - -c
      - |
        echo "rest.address: jobmanager" >> /opt/flink/conf/flink-conf.yaml
        echo "rest.port: 8081" >> /opt/flink/conf/flink-conf.yaml
        exec sql-client.sh embedded -i /sql/00_init.sql
    volumes:
      - ./sql:/sql
    # Run with:  docker compose run --rm sql-client
